version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: 'tele-collect'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
